os: osx
osx_image: xcode10.1
language: swift

script: 
# Development
- openssl enc -aes-256-cbc -base64 -pass pass:Demo -d -p -in scripts/certs/development-cert.cer.enc  -out scripts/certs/development-cert.cer
- openssl enc -aes-256-cbc -base64 -pass pass:Demo -d -p -in scripts/certs/development-key.p12.enc  -out scripts/certs/development-key.p12
- openssl enc -aes-256-cbc -base64 -pass pass:Demo -d -p -in scripts/certs/ProvProfile.mobileprovision.enc  -out scripts/certs/ProvProfile.mobileprovision

# Create custom keychain
- security create-keychain -p Demo ios-project-build.keychain
# Make the ios-build.keychain default, so xcodebuild will use it
- security default-keychain -s ios-project-build.keychain
# Unlock the keychain
- security unlock-keychain -p Demo ios-project-build.keychain
# Set keychain timeout to 1 hour for long builds
# see here
- security set-keychain-settings -t 3600 -l ~/Library/Keychains/ios-project-build.keychain



- security import ./scripts/certs/AppleWWDRCA.cer -k ios-project-build.keychain -A
- security import ./scripts/certs/development-cert.cer -k ios-project-build.keychain -A
- security import ./scripts/certs/development-key.p12 -k ios-project-build.keychain -P Demo -A

- mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
- cp "./scripts/certs/ProvProfile.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/

- xcodebuild archive -project GymApp.xcodeproj -scheme GymApp -configuration Release -derivedDataPath ./build -archivePath ./build/Products/GymApp.xcarchive
- xcodebuild -exportArchive -archivePath ./build/Products/GymApp.xcarchive -exportOptionsPlist ./scripts/exportOptions-Enterprise.plist -exportPath ./build/Products/IPA
